version: '3'

services:
  database:
    container_name: postgres
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped

  user-service:
    container_name: user-service
    image: user-service:latest
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/investview
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - database
      - discovery-service

  market-service:
    image: market-service:latest
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: .
      dockerfile: MarketService/Dockerfile
    ports:
      - "8081-8085:8080"
    depends_on:
      - discovery-service

  router-service:
    image: router-service:latest
    build:
      context: .
      dockerfile: RouterService/Dockerfile
    ports:
      - "8086:8080"
    depends_on:
      - discovery-service

  discovery-service:
    container_name: discovery-service
    image: discovery-service:latest
    build:
      context: .
      dockerfile: ServiceDiscovery/Dockerfile
    ports:
      - "8761:8761"

networks:
  database:
    driver: bridge